### ISSUE TITLE
Doesnt do anything on 1.19.2

### ISSUE THREAD

**Issue by palapapa** [TonimatasDEV/PacketFixerForge#10]
Mod version 1.1.1
[latest.log](https://github.com/TonimatasDEV/PacketFixerForge/files/12028698/latest.log)

**Comment by TonimatasDEV** [comment]
> Mod version 1.1.1 [latest.log](https://github.com/TonimatasDEV/PacketFixerForge/files/12028698/latest.log)

Fixed in 1.1.2

Download in https://www.curseforge.com/minecraft/mc-mods/packet-fixer/files
